// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNiCfyvX8Gb1rKkxxf-rGCi3KuCQthzgs',
    appId: '1:630979881620:web:907f87cc3e566326cea281',
    messagingSenderId: '630979881620',
    projectId: 'uptodo-app-ea6e8',
    authDomain: 'uptodo-app-ea6e8.firebaseapp.com',
    storageBucket: 'uptodo-app-ea6e8.appspot.com',
    measurementId: 'G-HRFPPG6MZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJSvJU39Loy5JLwS_ioyquKnIxQ-lnmUI',
    appId: '1:630979881620:android:a18df478619f0fb0cea281',
    messagingSenderId: '630979881620',
    projectId: 'uptodo-app-ea6e8',
    storageBucket: 'uptodo-app-ea6e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjgYeEekS8WLn6YYC8UMdaqwePqy9CjDg',
    appId: '1:630979881620:ios:4c246a1d319fa198cea281',
    messagingSenderId: '630979881620',
    projectId: 'uptodo-app-ea6e8',
    storageBucket: 'uptodo-app-ea6e8.appspot.com',
    iosBundleId: 'com.example.uptodoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjgYeEekS8WLn6YYC8UMdaqwePqy9CjDg',
    appId: '1:630979881620:ios:4c246a1d319fa198cea281',
    messagingSenderId: '630979881620',
    projectId: 'uptodo-app-ea6e8',
    storageBucket: 'uptodo-app-ea6e8.appspot.com',
    iosBundleId: 'com.example.uptodoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNiCfyvX8Gb1rKkxxf-rGCi3KuCQthzgs',
    appId: '1:630979881620:web:42887fcddac36617cea281',
    messagingSenderId: '630979881620',
    projectId: 'uptodo-app-ea6e8',
    authDomain: 'uptodo-app-ea6e8.firebaseapp.com',
    storageBucket: 'uptodo-app-ea6e8.appspot.com',
    measurementId: 'G-3GTKDX8FQW',
  );
}
